#!/usr/bin/env bash
source /etc/profile
curl http://localhost/reg/get_reg_daily_activity
curl http://localhost/pay/get_pay_daily_activity
curl http://localhost/get_web_hot_spot
curl http://localhost/class_tools_daily_activity/2
curl http://localhost/class_tools_daily_activity/3
curl http://localhost/class_tools_daily_activity/7
curl http://localhost/class_mode_daily_activity/QQ
curl http://localhost/class_mode_daily_activity/Skype
curl http://localhost/class_mode_daily_activity/ClassPlat
curl http://localhost/student_daily_activity/Android
curl http://localhost/student_daily_activity/Web
curl http://localhost/student_daily_activity/iOS
curl http://localhost/student_daily_activity/ClassPlat